import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { verify, log } from '../utils/utils.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const debugLogFilePath = path.join(__dirname, 'debug.log');

export const allTools = [
    {
        type: "function",
        name: "delegate",
        description: "Delegate a task to another specialized agent.",
        parameters: {
            type: "object",
            properties: {
                agent: { type: "string", enum: ["pointer", "instructor"], description: "The name of the agent to delegate to" },
                task: { type: "string", description: "The specific task description for the agent" }
            },
            required: ["agent", "task"],
            additionalProperties: false
        },
        strict: true
    },
    {
        type: "function",
        name: "verify_drone",
        description: "Verify the drone instructions by calling the verification endpoint.",
        parameters: {
            type: "object",
            properties: {
                instructions: { 
                    type: "array", 
                    items: { type: "string" },
                    description: "The list of drone instructions generated by the instructor agent" 
                }
            },
            required: ["instructions"],
            additionalProperties: false
        },
        strict: true
    }
];

export const createNativeHandlers = (agentName) => ({
    verify_drone: async ({ instructions }) => {
        log(`verify_drone instructions: ${JSON.stringify(instructions)}`, 'tool', false, debugLogFilePath);
        try {
            const response = await verify("drone", { instructions });
            const body = await response.json();
            const result = { status: response.status, body };
            log(`verify_drone response: ${JSON.stringify(result)}`, 'tool', false, debugLogFilePath);
            return JSON.stringify(result);
        } catch (error) {
            log(`verify_drone error: ${error.message}`, 'error', false, debugLogFilePath);
            return JSON.stringify({ error: error.message });
        }
    }
});
