import { verify } from '../utils/utils.js';

export const allTools = [
    {
        type: "function",
        name: "delegate",
        description: "Delegate a task to another specialized agent.",
        parameters: {
            type: "object",
            properties: {
                agent: { type: "string", enum: ["pointer", "instructor"], description: "The name of the agent to delegate to" },
                task: { type: "string", description: "The specific task description for the agent" }
            },
            required: ["agent", "task"],
            additionalProperties: false
        },
        strict: true
    },
    {
        type: "function",
        name: "verify_drone",
        description: "Verify the drone instructions by calling the verification endpoint.",
        parameters: {
            type: "object",
            properties: {
                instructions: { 
                    type: "array", 
                    items: { type: "string" },
                    description: "The list of drone instructions generated by the instructor agent" 
                }
            },
            required: ["instructions"],
            additionalProperties: false
        },
        strict: true
    }
];

export const createNativeHandlers = (agentName) => ({
    verify_drone: async ({ instructions }) => {
        try {
            const response = await verify("drone", { instructions });
            const body = await response.json();
            return JSON.stringify({ status: response.status, body });
        } catch (error) {
            return JSON.stringify({ error: error.message });
        }
    }
});
