import type { SeedTaskDefinition, WorkflowProjectMetadata } from '../types.js'

export const REPORT_V1_PROJECT: WorkflowProjectMetadata = {
  id: 'long-horizon-report',
  title: '# Long-Horizon Agent Report',
  description:
    'This project demonstrates multi-agent coordination for long-horizon report delivery.',
  deliverablePath: 'report/final-report.md',
}

export const buildReportV1SeedTasks = (): SeedTaskDefinition[] => [
  {
    filename: '01-decide-report-tone.md',
    id: 'decide-report-tone',
    title: 'Choose report tone and strategic narrative',
    owner: 'planner',
    priority: 'high',
    dependsOn: [],
    outputPath: 'notes/editorial-direction.md',
    body: [
      '## Objective',
      'Lock the narrative direction for a leadership audience.',
      '',
      '## Required workflow',
      '1. If `human_answer` is empty, call `request_human` with exactly two options:',
      '   - Option A: practical implementation playbook',
      '   - Option B: architecture-first strategic narrative',
      '2. After answer exists, write `notes/editorial-direction.md` including:',
      '   - selected option',
      '   - audience assumptions',
      '   - tone and voice guardrails',
      '   - anti-patterns to avoid',
      '',
      '## Definition of Done',
      '- `notes/editorial-direction.md` exists with explicit tone rules.',
    ].join('\n'),
  },
  {
    filename: '02-create-editorial-brief.md',
    id: 'create-editorial-brief',
    title: 'Create report brief and outline',
    owner: 'planner',
    priority: 'high',
    dependsOn: ['decide-report-tone'],
    outputPath: 'report/brief.md',
    body: [
      '## Objective',
      'Create a world-class writing brief and non-negotiable report outline.',
      '',
      '## Deliverables',
      '1. `report/brief.md` with:',
      '   - target reader',
      '   - core promise',
      '   - top objections to address',
      '   - desired decision from the reader',
      '2. `report/outline.md` with required top-level headings:',
      '   - # Executive Summary',
      '   - # 1. Context and Observational Memory',
      '   - # 2. Events and Heartbeat Architecture',
      '   - # 3. Implementation Blueprint',
      '   - # 4. Risks and Trade-offs',
      '   - # 5. Metrics and Rollout',
      '   - # References',
      '',
      '## Definition of Done',
      '- Both files exist and are specific enough for deterministic writing.',
    ].join('\n'),
  },
  {
    filename: '03-research-observational-memory.md',
    id: 'research-observational-memory',
    title: 'Research observational memory patterns',
    owner: 'researcher',
    priority: 'high',
    dependsOn: [],
    outputPath: 'notes/research/observational-memory.md',
    body: [
      '## Objective',
      'Gather high-confidence evidence on observer/reflector memory systems.',
      '',
      '## Requirements',
      '- Use web_search for external references.',
      '- Include practical implementation details, not only definitions.',
      '- Write `notes/research/observational-memory.md` with links and extraction notes.',
      '',
      '## Definition of Done',
      '- Research note exists and is ready for evidence-card extraction.',
    ].join('\n'),
  },
  {
    filename: '04-research-event-heartbeat.md',
    id: 'research-event-heartbeat',
    title: 'Research event-driven heartbeat orchestration',
    owner: 'researcher',
    priority: 'high',
    dependsOn: [],
    outputPath: 'notes/research/event-heartbeat.md',
    body: [
      '## Objective',
      'Gather high-confidence evidence on heartbeat orchestration and event-driven control.',
      '',
      '## Requirements',
      '- Use web_search for external references.',
      '- Cover leases, task claiming, waits, retries, and failure modes.',
      '- Write `notes/research/event-heartbeat.md` with links and extraction notes.',
      '',
      '## Definition of Done',
      '- Research note exists and is ready for evidence-card extraction.',
    ].join('\n'),
  },
  {
    filename: '05-build-evidence-cards.md',
    id: 'build-evidence-cards',
    title: 'Build evidence cards and citation index',
    owner: 'researcher',
    priority: 'high',
    dependsOn: ['research-observational-memory', 'research-event-heartbeat'],
    outputPath: 'notes/evidence/index.md',
    body: [
      '## Objective',
      'Convert research into reusable evidence cards for citation-safe writing.',
      '',
      '## Required workflow',
      '1. Read both research notes.',
      '2. Create at least 10 evidence cards in `notes/evidence/` named R001.md ... R010.md.',
      '3. Each card frontmatter must include: id, title, url, publisher, published_at, reliability.',
      '4. Create `notes/evidence/index.md` mapping claims to evidence IDs.',
      '',
      '## Definition of Done',
      '- Minimum 10 valid evidence cards exist.',
      '- Evidence index exists and is human-readable.',
    ].join('\n'),
  },
  {
    filename: '06-design-observational-memory-schema.md',
    id: 'design-observational-memory-schema',
    title: 'Design hand-drawn schema for observational memory',
    owner: 'designer',
    priority: 'high',
    dependsOn: ['research-observational-memory'],
    outputPath: 'notes/figures/observational-memory-schema.md',
    body: [
      '## Objective',
      'Create visual schema for observer + reflector memory flow.',
      '',
      '## Required workflow',
      '1. Generate schema image via create_image (hand_drawn_schema style).',
      '2. Analyze it via analyze_image and improve if needed.',
      '3. Write `notes/figures/observational-memory-schema.md` containing:',
      '   - exact image path',
      '   - embed markdown line for report sections',
      '   - concise caption',
      '   - interpretation bullets',
      '',
      '## Definition of Done',
      '- Figure package exists and points to a local image file in assets.',
    ].join('\n'),
  },
  {
    filename: '07-design-heartbeat-event-schema.md',
    id: 'design-heartbeat-event-schema',
    title: 'Design hand-drawn schema for heartbeat and events',
    owner: 'designer',
    priority: 'high',
    dependsOn: ['research-event-heartbeat'],
    outputPath: 'notes/figures/heartbeat-event-schema.md',
    body: [
      '## Objective',
      'Create visual schema for heartbeat loop, claims, and event flow.',
      '',
      '## Required workflow',
      '1. Generate schema image via create_image (hand_drawn_schema style).',
      '2. Analyze it via analyze_image and improve if needed.',
      '3. Write `notes/figures/heartbeat-event-schema.md` containing:',
      '   - exact image path',
      '   - embed markdown line for report sections',
      '   - concise caption',
      '   - interpretation bullets',
      '',
      '## Definition of Done',
      '- Figure package exists and points to a local image file in assets.',
    ].join('\n'),
  },
  {
    filename: '08-write-context-section.md',
    id: 'write-context-section',
    title: 'Write context and memory section with citations',
    owner: 'writer',
    priority: 'high',
    dependsOn: [
      'create-editorial-brief',
      'build-evidence-cards',
      'design-observational-memory-schema',
    ],
    outputPath: 'report/sections/01-context-and-memory.md',
    body: [
      '## Objective',
      'Write section 1 with executive-grade narrative and rigorous citations.',
      '',
      '## Inputs',
      '- `report/brief.md`',
      '- `report/outline.md`',
      '- `notes/evidence/index.md`',
      '- `notes/figures/observational-memory-schema.md`',
      '',
      '## Mandatory citation contract',
      '- Include at least 5 citation markers like [R001].',
      '- Include inline source links for key claims.',
      '- Include the figure embed line from figure package exactly as provided.',
      '- End section with a 3-bullet implementation checklist.',
      '',
      '## Definition of Done',
      '- Section file exists, follows outline, and meets citation contract.',
    ].join('\n'),
  },
  {
    filename: '09-write-events-section.md',
    id: 'write-events-section',
    title: 'Write events and heartbeat section with citations',
    owner: 'writer',
    priority: 'high',
    dependsOn: [
      'create-editorial-brief',
      'build-evidence-cards',
      'design-heartbeat-event-schema',
    ],
    outputPath: 'report/sections/02-events-and-heartbeat.md',
    body: [
      '## Objective',
      'Write section 2 with executive-grade narrative and rigorous citations.',
      '',
      '## Inputs',
      '- `report/brief.md`',
      '- `report/outline.md`',
      '- `notes/evidence/index.md`',
      '- `notes/figures/heartbeat-event-schema.md`',
      '',
      '## Mandatory citation contract',
      '- Include at least 5 citation markers like [R001].',
      '- Include inline source links for key claims.',
      '- Include the figure embed line from figure package exactly as provided.',
      '- End section with a 3-bullet operational checklist.',
      '',
      '## Definition of Done',
      '- Section file exists, follows outline, and meets citation contract.',
    ].join('\n'),
  },
  {
    filename: '10-assemble-final-report.md',
    id: 'assemble-final-report',
    title: 'Assemble final report',
    owner: 'planner',
    priority: 'critical',
    dependsOn: ['write-context-section', 'write-events-section'],
    outputPath: 'report/final-report.md',
    body: [
      '## Objective',
      'Assemble a leadership-ready report from sections and references.',
      '',
      '## Inputs',
      '- `report/sections/01-context-and-memory.md`',
      '- `report/sections/02-events-and-heartbeat.md`',
      '- `report/outline.md`',
      '- `notes/evidence/index.md`',
      '- `notes/figures/observational-memory-schema.md`',
      '- `notes/figures/heartbeat-event-schema.md`',
      '',
      '## Requirements',
      '- Include all top-level headings from outline.',
      '- Include both figure embeds from figure packages.',
      '- Include # References section mapping cited IDs to source links.',
      '- Include sections 3/4/5 with concrete implementation guidance and trade-offs.',
      '',
      '## Definition of Done',
      '- Final report exists and is structurally complete for editorial QA.',
    ].join('\n'),
  },
]
