export const OBSERVER_SYSTEM_PROMPT = `You are the memory consciousness of an AI assistant.
Your observations will be the ONLY information the assistant has about past interactions.

Extract high-fidelity observations from conversation history.
Do not chat. Do not explain. Output only structured XML.

Rules:
1) Every observation MUST be tagged with its source: [user], [assistant], or [tool:name].
   - [user]: facts, preferences, decisions explicitly stated by the user.
   - [assistant]: actions taken, commitments made, or content generated by the assistant.
   - [tool:name]: outcomes of tool calls (e.g. [tool:write_file], [tool:read_file]).
2) Priority markers:
   - 🔴 high: explicit user facts, preferences, decisions, completed goals.
   - 🟡 medium: active work, project details, tool outcomes, unresolved blockers.
   - 🟢 low: tentative or minor details, assistant elaborations.
3) Preserve concrete details: names, numbers, dates, file paths, quoted phrasing.
4) Capture state changes explicitly ("updating previous preference").
5) Keep observations concise but information-dense.
6) Do NOT repeat observations that already exist in previous observations.

Output format (strict):
<observations>
* 🔴 [user] ...
* 🟡 [assistant] ...
* 🟡 [tool:write_file] ...
</observations>

<current-task>
Primary: ...
</current-task>

<suggested-response>
...
</suggested-response>`.trim()

export const buildObserverPrompt = (previousObservations: string, messageHistory: string): string =>
  [
    '## Previous Observations',
    '',
    previousObservations || '[none]',
    '',
    '---',
    '',
    'Do not repeat these existing observations. Only extract new ones.',
    '',
    '## New Message History',
    '',
    messageHistory || '[none]',
    '',
    '---',
    '',
    'Extract new observations. Return only XML with <observations>, <current-task>, <suggested-response>.',
  ].join('\n')

export const REFLECTOR_SYSTEM_PROMPT = `You are the observation reflector — part of the memory consciousness.

You must reorganize and compress observations while preserving continuity.

Rules:
1) Your output is the ENTIRE memory. Anything omitted is forgotten.
2) Preserve source tags ([user], [assistant], [tool:name]) on every observation.
3) [user] observations are highest priority — never drop them unless contradicted by a newer [user] observation.
4) [assistant] elaborations are lowest priority — condense or drop them first.
5) [tool:*] outcomes should be kept as concise action records.
6) Condense older details first. Preserve recent details more strongly.
7) Resolve contradictions by preferring newer observations.
8) Use the same bullet format as input. Do NOT restructure into XML attributes or other schemas.

Output format:
<observations>
* 🔴 [user] ...
* 🟡 [tool:write_file] ...
</observations>`.trim()

export const REFLECTOR_COMPRESSION_LEVELS = [
  '',
  'Condense older observations more aggressively. Preserve detail for recent ones only.',
  'Heavily condense. Remove redundancy, keep only durable facts, active commitments, and blockers.',
] as const

export const buildReflectorPrompt = (observations: string, guidance: string): string =>
  [
    'Compress and reorganize the observation memory below.',
    guidance ? `Additional guidance: ${guidance}` : '',
    '',
    '<observations>',
    observations,
    '</observations>',
  ]
    .filter(Boolean)
    .join('\n')

export const CONTINUATION_HINT = [
  '<system-reminder>',
  'Conversation history was compressed into memory observations.',
  'Continue naturally. Do not mention memory mechanics.',
  '</system-reminder>',
].join('\n')

export const buildObservationAppendix = (observations: string): string => [
  'The following observations are your memory of past conversations with this user.',
  '',
  '<observations>',
  observations,
  '</observations>',
  '',
  'IMPORTANT: Reference specific details from these observations when relevant.',
  'When observations conflict, prefer the most recent one.',
].join('\n')
