import type { SeedTaskDefinition, WorkflowProjectMetadata } from '../types.js'

export const REPORT_V2_PROJECT: WorkflowProjectMetadata = {
  id: 'local-inference-hardware-report',
  title: '# MacBook vs PC for Local AI Inference (2026)',
  description:
    'A short practical report comparing MacBook and PC options for local AI inference workloads.',
  deliverablePath: 'report/local-inference-report.md',
}

export const buildReportV2SeedTasks = (): SeedTaskDefinition[] => [
  {
    filename: '01-research-broad-landscape.md',
    id: 'research-broad-landscape',
    title: 'Research broad landscape: MacBook vs PC for local inference',
    owner: 'researcher',
    priority: 'high',
    dependsOn: [],
    outputPath: 'notes/research/local-inference-landscape.md',
    body: [
      '## Objective',
      'Build a broad, up-to-date landscape of local inference hardware choices in 2026.',
      '',
      '## Requirements',
      '- Use `web_search` for external sources.',
      '- Cover at least: memory/VRAM constraints, inference speed, thermals/noise, portability, and price tiers.',
      '- Include practical notes for running coding agents and local LLM stacks.',
      '- Write `notes/research/local-inference-landscape.md` with source links.',
      '',
      '## Definition of Done',
      '- Research note exists with actionable comparisons and linked sources.',
    ].join('\n'),
  },
  {
    filename: '02-research-narrow-criteria.md',
    id: 'research-narrow-criteria',
    title: 'Narrow to decision criteria and buyer scenarios',
    owner: 'researcher',
    priority: 'high',
    dependsOn: ['research-broad-landscape'],
    outputPath: 'notes/research/local-inference-criteria.md',
    body: [
      '## Objective',
      'Convert broad research into a concrete decision framework.',
      '',
      '## Requirements',
      '- Define 3 personas: student/learner, solo builder, small team lead.',
      '- For each persona, recommend default setup and fallback setup.',
      '- Include a concise comparison table with clear trade-offs.',
      '- Write `notes/research/local-inference-criteria.md` with source-backed rationale.',
      '',
      '## Definition of Done',
      '- Criteria note exists and is specific enough for deterministic writing.',
    ].join('\n'),
  },
  {
    filename: '03-design-decision-matrix.md',
    id: 'design-decision-matrix',
    title: 'Design decision matrix visual',
    owner: 'designer',
    priority: 'high',
    dependsOn: ['research-narrow-criteria'],
    outputPath: 'notes/figures/local-inference-decision-matrix.md',
    body: [
      '## Objective',
      'Create a hand-drawn decision matrix visual for hardware selection.',
      '',
      '## Required workflow',
      '1. Generate figure via `create_image` with `hand_drawn_schema` style.',
      '2. Validate via `analyze_image` and iterate if needed.',
      '3. Write `notes/figures/local-inference-decision-matrix.md` including:',
      '   - exact image path',
      '   - markdown embed line',
      '   - short caption',
      '',
      '## Definition of Done',
      '- Figure package exists and references a local asset path.',
    ].join('\n'),
  },
  {
    filename: '04-design-local-inference-flow.md',
    id: 'design-local-inference-flow',
    title: 'Design local inference workflow visual',
    owner: 'designer',
    priority: 'high',
    dependsOn: ['research-broad-landscape'],
    outputPath: 'notes/figures/local-inference-flow.md',
    body: [
      '## Objective',
      'Create a hand-drawn visual of a practical local inference setup flow.',
      '',
      '## Required workflow',
      '1. Generate figure via `create_image` with `hand_drawn_schema` style.',
      '2. Validate via `analyze_image` and iterate if needed.',
      '3. Write `notes/figures/local-inference-flow.md` including:',
      '   - exact image path',
      '   - markdown embed line',
      '   - short caption',
      '',
      '## Definition of Done',
      '- Figure package exists and references a local asset path.',
    ].join('\n'),
  },
  {
    filename: '05-write-landscape-section.md',
    id: 'write-landscape-section',
    title: 'Write section: broad landscape and trade-offs',
    owner: 'writer',
    priority: 'high',
    dependsOn: ['research-broad-landscape', 'design-local-inference-flow'],
    outputPath: 'report/sections/01-landscape.md',
    body: [
      '## Objective',
      'Write a short, clear section describing the broad landscape and key trade-offs.',
      '',
      '## Inputs',
      '- `notes/research/local-inference-landscape.md`',
      '- `notes/figures/local-inference-flow.md`',
      '',
      '## Requirements',
      '- Keep section concise (target 350-500 words).',
      '- Include inline source links for key claims.',
      '- Include figure embed from the figure package.',
      '',
      '## Definition of Done',
      '- Section file exists and is concise, useful, and source-backed.',
    ].join('\n'),
  },
  {
    filename: '06-write-recommendation-section.md',
    id: 'write-recommendation-section',
    title: 'Write section: recommendations by persona',
    owner: 'writer',
    priority: 'high',
    dependsOn: ['research-narrow-criteria', 'design-decision-matrix'],
    outputPath: 'report/sections/02-recommendations.md',
    body: [
      '## Objective',
      'Write practical recommendations for who should buy what and why.',
      '',
      '## Inputs',
      '- `notes/research/local-inference-criteria.md`',
      '- `notes/figures/local-inference-decision-matrix.md`',
      '',
      '## Requirements',
      '- Keep section concise (target 400-600 words).',
      '- Provide clear recommendations for each persona.',
      '- Include inline source links and the matrix figure embed.',
      '',
      '## Definition of Done',
      '- Section file exists with concrete, actionable recommendations.',
    ].join('\n'),
  },
  {
    filename: '07-assemble-short-report.md',
    id: 'assemble-short-report',
    title: 'Assemble short final report',
    owner: 'planner',
    priority: 'critical',
    dependsOn: ['write-landscape-section', 'write-recommendation-section'],
    outputPath: 'report/local-inference-report.md',
    body: [
      '## Objective',
      'Assemble a short final report from prepared sections.',
      '',
      '## Inputs',
      '- `report/sections/01-landscape.md`',
      '- `report/sections/02-recommendations.md`',
      '',
      '## Requirements',
      '- Include headings:',
      '  - # Executive Summary',
      '  - # 1. Landscape',
      '  - # 2. Recommendations by Persona',
      '  - # 3. Quick Start Checklist',
      '  - # References',
      '- Keep report compact (target <= 1200 words, excluding references).',
      '- Preserve image embeds and source links.',
      '',
      '## Definition of Done',
      '- Final report exists and is structurally complete.',
    ].join('\n'),
  },
  {
    filename: '08-review-short-report.md',
    id: 'review-short-report',
    title: 'Review and polish final report',
    owner: 'editor',
    priority: 'high',
    dependsOn: ['assemble-short-report'],
    outputPath: 'report/review-notes.md',
    body: [
      '## Objective',
      'Perform a final editorial pass on the short report.',
      '',
      '## Required workflow',
      '1. Review `report/local-inference-report.md` for clarity, consistency, and factual caution.',
      '2. Fix broken references, links, and figure paths if needed.',
      '3. Keep language concise and practical.',
      '4. Write `report/review-notes.md` with key edits performed.',
      '',
      '## Definition of Done',
      '- Final report is polished.',
      '- Review notes file exists.',
    ].join('\n'),
  },
]
